### ISSUE TITLE
Problems when starting

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRef-Word-Addin#28]
1. `yarn start` asks
> ? Allow localhost loopback for Microsoft Edge WebView? Yes/No

Regardless of what I choose, always Word opens and the following error is displayed in the sidepane:
![image](https://user-images.githubusercontent.com/5037600/121387560-0d6e6180-c94b-11eb-8d5f-d3d8671f58ca.png)

2. For the web installation, is it possible to specify the path in an `.env` file, because otherwise the package.json is modified which may lead to accidentally commiting the url. Could we specify a default, globally accessible document so that testing is easier?
3. For the web installation, there is also an error
![image](https://user-images.githubusercontent.com/5037600/121388818-13b10d80-c94c-11eb-9139-4299de21e8ef.png)

I guess this comes from another error " Error: listen EADDRINUSE: address already in use 127.0.0.1:3000", have to investigate this.

4. For both `start` and `start:web`, I need admin rights? Is this really necessary?
5. The manual installation in Word web works. However, after opening the sidebar I get another error:

![image](https://user-images.githubusercontent.com/5037600/121389293-8a4e0b00-c94c-11eb-8183-cf8f918b4ab1.png)

**Comment by Siedlerchr** [comment]
Locally, on my mac I can't get it to run either: 
<img width="355" alt="grafik" src="https://user-images.githubusercontent.com/320228/121414934-7b288680-c967-11eb-8ac8-bffb1ce5eb64.png">

And I also suggest using dotenv (.env for storing config)

**Comment by tobiasdiez** [comment]
I tried different ways described in the documentation to get it install in the desktop version as well. None worked, and in the process I discovered that my university disabled the Office store. This might be the reason - I've contacted them and let's see if this gets resolved.

The manual web installation works now, but I think, I needed to run `yarn dev-server` the first time with admin rights.

**Comment by tobiasdiez** [comment]
This is working now, modulo https://github.com/OfficeDev/Office-Addin-Scripts/issues/769.
