### ISSUE TITLE
Add authorization

### ISSUE THREAD

**Issue by mohit038** [JabRef/JabRef-Word-Addin#3]
Let users log in directly from the add-in, and to create a new account, redirect to jabref-online.

**Comment by tobiasdiez** [comment]
For the logout, you first call the `logout` mutation and then invalidate the cache using `clearStore` as described here: https://www.apollographql.com/docs/react/networking/authentication/#reset-store-on-logout

**Comment by tobiasdiez** [comment]
@mohit038 The logout has been also implemented, right? So can this be closed or is there still something left to do?
