### ISSUE TITLE
Add linting for js and graphql

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRef-Word-Addin#42]
Eslint + prettifier.

TODO:
- [ ] review rules that has been turned off
- [ ] add linting for graphql (?) as e.g in https://github.com/JabRef/JabRefOnline/pull/166

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Perhaps we can work our way towards using some of the AirBnB's ESLint configs https://mikelow.dev/blog/how-to-keep-airbnb-eslint-config-in-typescript (there is a hooks extension as well). More detailed information can be found on https://airbnb.io/javascript/react/. I believe it can work well with TypeScript, even without using the [recommended](https://github.com/airbnb/javascript#airbnb-javascript-style-guide-) babel
In addition to what that article states, we'll probably need to add `react` and `react/hooks` to `plugins: {...`.
At the moment it collides with how `react-hot-loader` is being used, but perhaps that can be ignored on a line-by-line basis until #73 is reviewed.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I'm not suggesting following the AirBnB configs blindly. If there is something that doesn't make sense to us we can always disable that setting.

Other configs that I'd consider interesting (but I have 0 experience with) is [unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn#eslint-plugin-unicorn-) and [`recommended-requiring-type-checking`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#recommended-configs) and as they are not part of JabRef online configs either perhaps we should skip them?

**Comment by Siedlerchr** [comment]
One thing I changed in my prettier config for another project was the "print-width". Default it's 80. I suggest something over 120 or so. Otherwise, you will have uncessary wrappings of lines. And today most screens have usually a larger width than a height.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I'd +1 that, I think the office settings is 120 but perhaps they easily get overwritten.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
**note to myself** we need to review the use of `__dirname` from `.env` https://github.com/OfficeDev/Office-Addin-Scripts/blob/27c98c25d9740f3fd184e04f234ad463a8221647/packages/office-addin-lint/src/lint.ts#L15
