### ISSUE TITLE
CRLF line endings in `node_modules`

### ISSUE THREAD

**Issue by k3KAW8Pnf7mkmdSMPHz27** [JabRef/JabRef-Word-Addin#65]
Not sure what is a good option here, I'd appreciate some feedback.

#### Incorrect line endings after installing with yarn

This creates issues with getting validate/lint/prettier to run.
For the most detailed/relevant GitHub issues, see

1. https://github.com/yarnpkg/yarn/issues/5480
2. https://github.com/OfficeDev/Office-Addin-Scripts/issues/168

#### Workarounds

1. Use npm to install, which is quite unsatisfactory.
2. If we just want to test it locally on Mac OS, [dos2unix exist on homebrew](https://formulae.brew.sh/formula/dos2unix), similar to https://github.com/yarnpkg/yarn/issues/5480#issuecomment-464966030 (I haven't tried this yet)
3. Add some post-install script that converts CRLF -> LF in `node_modules` and enforce [LF allover](https://darekkay.com/blog/windows-lf-line-endings/). An example of the script could be https://www.darraghoriordan.com/2021/05/18/env-node-r-no-such-file-or-directory/

**Comment by tobiasdiez** [comment]
Thanks for the investigation. I guess the post-install script should be the easiest solution. The files that need to be fixed can be found in https://github.com/OfficeDev/Office-Addin-Scripts/issues/168#issuecomment-547982924
