### ISSUE TITLE
Improve handling of selection state

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabRef-Word-Addin#75]
Think about a nice way to handle the state of selected items, and decide where this should be done (in the reference list control, in a wrapper, in the dashboard or in a global state).

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I think perhaps we should consider wrapping the list in `JSX.Element`s. Right now the main issue is that the component that is rendered is created by the function given to `<List onRenderCell={}>` which must be

```
function (item: T, index: number, isScrollable: boolean) => React.ReactNode // JSX.Element should be fine
```

At the moment `item` is a BibEntry, and we are [discouraged from reassigning its attributes](https://eslint.org/docs/rules/no-param-reassign).

Perhaps something can be done if `T = JSX.Element` and `onRenderCell` is the identity, e.g., `<List items={JSXItems} onRenderCell={(item) => item}>`.

I might have to think about it a bit more to suggest something more concrete.

**Comment by tobiasdiez** [comment]
Thanks for the comments. Note that this issue is more about the selection state and not primarily about the rendering of the entry. 

I had a look at the Fluent UI and they have a ISelection interface that looks very promising: https://docs.microsoft.com/en-us/javascript/api/utilities/iselection?view=office-ui-fabric-react-latest
The DetailList exposes this for example. See https://docs.microsoft.com/en-us/javascript/api/examples/detailslist/detailslist?view=office-ui-fabric-react-latest for how it's used. 
So what do you think about having a similar props in the ReferenceList?
