### ISSUE TITLE
Edit citation

### ISSUE THREAD

**Issue by mohit038** [JabRef/JabRef-Word-Addin#8]
Edit reference before inserting it or edit citations in the document, i.e., add page no, prefix, suffix, suppress Authors, etc.

**Comment by tobiasdiez** [comment]
I had a look, and you are right. The API doesn't seem to have a nice way to get notified about losing focus on an content control.
So please go ahead and open an issue at the office-js repo.

Workarounds may include:
- Using the documentSelectionChanged handler: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet#detect-changes-in-the-selection
- Check the selection every few ms: https://github.com/shweaver-MSFT/GrammaR/blob/7a76eff72bbfd91e8254e2222b1a30730882e0d1/external/M365AddInToolkit/WordDocumentManager.js#L153-L163
